# Generated by Django 3.2.6 on 2021-09-07 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=1250, null=True)),
                ('cp', models.CharField(blank=True, max_length=4, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('cuil_cuit', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=2055)),
                ('state', models.IntegerField(default=0)),
                ('image_one', models.ImageField(blank=True, null=True, upload_to='articles/images/')),
                ('image_two', models.ImageField(blank=True, null=True, upload_to='articles/images/')),
                ('image_three', models.ImageField(blank=True, null=True, upload_to='articles/images/')),
                ('image_four', models.ImageField(blank=True, null=True, upload_to='articles/images/')),
                ('image_five', models.ImageField(blank=True, null=True, upload_to='articles/images/')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
