# Generated by Django 3.2.6 on 2021-08-24 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('lastname', models.CharField(max_length=40)),
                ('location', models.CharField(blank=True, max_length=1250, null=True)),
                ('cp', models.CharField(blank=True, max_length=4, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('cuil_cuit', models.CharField(blank=True, max_length=10, null=True)),
                ('mail', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=40)),
                ('user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
