# Generated by Django 3.2.6 on 2021-08-24 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
    ]
