# Generated by Django 3.2.6 on 2021-08-24 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0002_remove_profile_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
