# Generated by Django 3.2.6 on 2021-09-30 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sitio', '0004_auto_20210929_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canje',
            name='article_one',
        ),
        migrations.RemoveField(
            model_name='canje',
            name='article_two',
        ),
        migrations.AddField(
            model_name='canje',
            name='articles_assignee',
            field=models.ManyToManyField(related_name='assignee', to='sitio.Article'),
        ),
        migrations.AddField(
            model_name='canje',
            name='articles_creator',
            field=models.ManyToManyField(related_name='creator', to='sitio.Article'),
        ),
        migrations.AddField(
            model_name='canje',
            name='state',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='canje',
            name='user_assignee',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='canje',
            name='user_creator',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
