# Generated by Django 3.2.6 on 2021-09-05 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0005_auto_20210904_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_one',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to=''),
        ),
    ]
