# Generated by Django 3.2.8 on 2021-10-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0007_notification_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
