# Generated by Django 3.2.6 on 2021-09-05 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0008_auto_20210904_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_five',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_four',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_one',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_three',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_two',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
