# Generated by Django 3.2.6 on 2021-09-06 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0009_auto_20210905_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_five',
            field=models.ImageField(blank=True, null=True, upload_to='articles/images/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_four',
            field=models.ImageField(blank=True, null=True, upload_to='articles/images/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_one',
            field=models.ImageField(blank=True, null=True, upload_to='articles/images/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_three',
            field=models.ImageField(blank=True, null=True, upload_to='articles/images/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_two',
            field=models.ImageField(blank=True, null=True, upload_to='articles/images/'),
        ),
    ]
