# Generated by Django 3.2.8 on 2021-10-21 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0010_alter_canje_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canje',
            name='notification',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitio.notification'),
        ),
    ]
