# Generated by Django 3.2.8 on 2021-10-22 22:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0015_auto_20211022_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='timestamp2',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
