# Generated by Django 3.2.8 on 2021-10-23 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0017_auto_20211023_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='messages',
        ),
        migrations.AddField(
            model_name='chat',
            name='messages',
            field=models.ManyToManyField(blank=True, to='sitio.Message'),
        ),
    ]
